name: redis
adopt-info: redis
summary: Redis is used as a database, cache and message broker. # 79 char long summary
description: |
  Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker. |
  It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs, geospatial indexes with radius queries and streams. |
  Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster. |
  |
  Check out https://redis.io/ for more information.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20

apps:
  server:
    command: usr/bin/redis-server
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  cli:
    command: usr/bin/redis-cli
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  benchmark:
    command: usr/bin/redis-benchmark
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  check-aof:
    command: usr/bin/redis-check-aof
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  check-rdb:
    command: usr/bin/redis-check-rdb
    plugs:
      - network
      - network-bind
      - network-observe
      - home
  sentinel:
    command: usr/bin/redis-sentinel
    plugs:
      - network
      - network-bind
      - network-observe
      - home

parts:
  redis:
    plugin: make
    source: redis/
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr
      export CC=${SNAPCRAFT_ARCH_TRIPLET}-gcc
      export DEB_HOST_GNU_TYPE=${SNAPCRAFT_ARCH_TRIPLET}
      make -j4 BUILD_TLS=yes
      PREFIX=${SNAPCRAFT_PART_INSTALL}/usr make BUILD_TLS=yes install
      VER=`sed -n 's/^.* REDIS_VERSION "\(.*\)"$/\1/g p' < src/version.h`
      if [ "$VER" = "999.999.999" ]; then
          GITSHA=`sed -n 's/^.* REDIS_GIT_SHA1 "\(.*\)"$/\1/g p' < src/release.h`
          VER="unstable-$GITSHA"
      fi
      snapcraftctl set-version $VER
    build-packages:
      - on amd64:
        - to arm64:
          - libssl-dev:arm64
        - to amd64:
          - libssl-dev
