name: Tagged Packages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-24.04
          - architecture: arm64
            runner: ubuntu24-arm64-4-16

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Determine version
      run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v4
      with:
        repository: redis/redis
        path: redis
        ref: ${{ env.VERSION }}
  
    - name: Setup Snapcraft
      run: |
        sudo snap install snapcraft --classic

    - uses: canonical/setup-lxd@v0.1.2
    - name: Build Snap
      env:
        SNAPCRAFT_BUILD_INFO: 1
      run: |
        sudo snapcraft

    - name: Upload
      run: |
          for f in *.snap; do snapcraft upload --release=stable $f; done
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{secrets.SNAP_TOKEN}}
